helptext <- reactive(
  data.table(
    tab = c("tab_home",
            "tab_home",
            "v_species",
            "v_species",
            "v_species",
            "DeG",
            "DeG",
            "DeG",
            "DeG",
            "DeG",
            "DeG",
            "DeG",
            "DeG",
            "DeG",
            "metabolic_tab",
            "metabolic_tab",
            "metabolic_tab",
            "metabolic_tab",
            "metabolic_tab",
            "metabolic_tab",
            "metabolic_tab",
            "metabolic_tab",
            "flux_tab",
            "flux_tab",
            "flux_tab",
            "flux_tab",
            "flux_tab",
            "flux_tab",
            "flux_tab",
            "flux_tab",
            "analy2",
            "analy2",
            "analy2",
            "analy2",
            "analy2",
            "analy3",
            "analy3",
            "analy3",
            "analy3",
            "analy3",
            "analy3",
            "analy6",
            "analy6",
            "analy6",
            "analy6",
            "analy6",
            "analy4",
            "analy4",
            "analy4",
            "analy4",
            "cell_line",
            "cell_type",
            "cell_type",
            "cancerModel",
            "cancerModel",
            "cancerModel",
            "cancerModel",
            "cancerModel",
            "cancerModel",
            "cancerModel",
            "cancerModel",
            "cancerModel",
            "cancerModel",
            "strucPro",
            "strucPro",
            "strucPro",
            "strucPro",
            "strucPro",
            "strucPro",
            "strucPro",
            "strucPro",
            "strucPro",
            "drug2",
            "drug2",
            "drug1",
            "geneDrug"
    ),
    
    step = c("1",
             "2",
             "1",
             "2",
             "3",
             "1",
             "2",
             "3",
             "4",
             "5",
             "6",
             "7",
             "8",
             "9",
             "1",
             "2",
             "3",
             "4",
             "5",
             "6",
             "7",
             "8",
             "1",
             "2",
             "3",
             "4",
             "5",
             "6",
             "7",
             "8",
             "1",
             "2",
             "3",
             "4",
             "5",
             "1",
             "2",
             "3",
             "4",
             "5",
             "6",
             "1",
             "2",
             "3",
             "4",
             "5",
             "1",
             "2",
             "3",
             "4",
             "1",
             "1",
             "2",
             "1",
             "2",
             "3",
             "4",
             "5",
             "6",
             "7",
             "8",
             "9",
             "10",
             "1",
             "2",
             "3",
             "4",
             "5",
             "6",
             "7",
             "8",
             "9",
             "1",
             "2",
             "1",
             "1"
    ),
    
    element = c("#home_donut",
                "#home_human",
                "#filtered_onc",
                "#PPI_onc",
                "#runVisPPI",
                "#dataChoice",
                "#cancers",
                "#logFCcut",
                "#qvalcut",
                "#AnalTy",
                "#runAnalys",
                "#analyTab",
                "#plotS",
                "#userinputDif",
                "#metabolic1",
                "#userinput",
                "#metabolic1",
                "#metabolic1",
                "#kgene",
                "#runmetabolic",
                "#metabolic2",
                "#metabolic3",
                "#flux1",
                "#flux1",
                "#addRowBtn",
                "#removeRowBtn",
                "#editableTable",
                "#runflux",
                "#flux3",
                "#flux4",
                "#Enrich",
                "#Enrich",
                "#Enrich",
                "#runEnrich",
                "#Enrich2",
                "#Survival",
                "#Survival",
                "#runSurv",
                "#IdGene",
                "#inVarGene",
                "#runSurv2",
                "#Imsig",
                "#runImSig",
                "#imSigBar",
                "#imSigBar",
                "#imSigRes",
                "#SNV",
                "#SNV",
                "#GeneSize",
                "#runSNV",
                "#searchCell",
                "#celltypeS",
                "#cellMarkers",
                "#choseJimena",
                "#runGraphml",
                "#runJimena",
                "#strt",
                "#end",
                "#val",
                "#add_pert",
                "#remove_per",
                "#jimedit",
                "#jimena_table",
                "#alphafold2",
                "#pdb_name",
                "#download_btn",
                "#selection",
                "#alphafold2",
                "#alphafold2",
                "#alphafold2",
                "#backgroundColor",
                "#screenshot",
                "#choseDrug",
                "#searchDrugName",
                "#drugTissue",
                "#searchBttn"
    ),
    intro = c("Oncolytic virus list",
              "TCGA data cases size",
              "Please choose the specific oncolytic virus you are interested in.",
              "Select the oncolytic virus type for displaying interactions between human and viral proteins.",
              "Click the search button to proceed.",
              "You can perform expression analysis by selecting TCGA data. As a result of the analysis, a table, volcanoplot, violin plot and PCA plot are presented. Or you can create volcanoplot by uploading your own expressed data. If you have a GSE ID, you can perform expression analysis with the data obtained from GEO.",
              "For TCGA-GTEX data; Choose the cancer type from the provided list.",
              "Specify the logFC values.",
              "Specify the q-value.",
              "Select the type of analysis you'd like to perform.",
              "Click the 'Run' button to initiate the differential expression analysis.",
              "View the results in the analysis table.",
              "Choose the type of plot you'd like to generate.",
              "If you want to create a volcano plot using your own DEG data, continue with the use own data option.",
              "Select the cancer data from the available options.",
              "If you prefer to use your own data, you can upload it here.",
              "Choose the network type for analysis.",
              "Select the desired topology.",
              "Specify the number of genes you'd like to include.",
              "Run the metabolic analysis with your selected parameters.",
              "You can now view all the results.",
              "The metabolic network with pathways will be displayed.",
              "Select the Flux analysis type.",
              "Upload your .xml or .sbml file here.",
              "If you wish to adjust the lower/upper bounds of reduction, you can input values into the table.",
              "If you want to remove the lower/upper bounds of reduction, you can add values into the table.",
              "Here is your created scenario table for flux analysis.",
              "Click the 'Run' button to start the analysis.",
              "You can view the flux results, optimization, and summary of the analysis.",
              "Visualize the metabolic flux network.",
              "Select the cancer data for analysis.",
              "Specify the logFC value.",
              "Choose the q-value.",
              "Click the 'Run' button to start the enrichment analysis.",
              "Select the GO enrichment categories: biological process, molecular function, or cellular component outputs.",
              "Choose the tissue type.",
              "Select the clinical feature for survival analysis.",
              "Click the 'Plot' button to generate the survival graph.",
              "You can also create gene-specific survival graphs. Select Ensembl ID or Gene Name.",
              "Choose the related gene.",
              "Click the 'Plot' button to generate the survival graph.",
              "Select the tissue type.",
              "Click the 'Run' button to proceed.",
              "You can select the immune cell type.",
              "You can view the results of the immune signature analysis on network tab.",
              "View the results in the analysis table.",
              "Select the cancer tissue type.",
              "Choose the type of plot you'd like to generate.",
              "Specify the top gene size.",
              "Click the 'Plot' button to generate the graph.",
              "Search for your specific cell line.",
              "Select the tissue type.",
              "Choose the cell types for gene markers.",
              "Do you already have a signaling network? Would you like to search within the data available in the Cat-E database? Interested in viewing sample data?",
              "Click the 'Convert Graphml' button.",
              "Click 'Run Jimena'.",
              "A reactive node list will be generated. Select the nodes you wish to add from there and set the start time.",
              "Set the end time.",
              "Set the activation value. Assigning a value of 1 will simulate overexpression, while a value of 0 will knock out the node.",
              "Click the 'Add Perturbation' button to include the selected nodes in your perturbation list.",
              "Click the 'Run Analysis' button again to view the modified graph.",
              "You can edit the signaling table as needed.",
              "You can download the output.",
              "Please check the options for your structure.",
              "Please enter the Uniprot ID or PDB ID here.",
              "Click the 'Search' button.",
              "Specify the relevant range.",
              "Select the structure type.",
              "Choose the type of surface.",
              "Select the type of ligand.",
              "You have the option to change the background color.",
              "You can save the protein structure as a PNG file.",
              "Select what you would like to search for.",
              "Search your drug name",
              "Choose the tissue for drug data.",
              "Search for genes to display the list of available drugs."
    )
  )
)